### PR TITLE
Pull request for WAZO-2569-meeting-progress-event

### PR DESCRIPTION
**Pull request by sduthil**
Depends-On: https://github.com/wazo-platform/xivo-bus/pull/45

## tests: allow live modification of mock-command

Why:

* Avoid having to rebuild docker image

## request handlers: add request uuid

Why:

* In order to know what reload corresponds to what request

## request handlers: add new request completed event with context

Why:

* Avoid the calling service to remember the request context (more
stateless)

### CODE REVIEW

**Comment by sduthil** [comment]
recheck

**Comment by sduthil** [comment]
recheck

**Comment by sduthil** [comment]
Currently, Zuul cannot mount Depends-On in Python2 projects, so the integration tests will fail on Zuul.
I've opened another PR to fix this.

**Comment by sduthil** [comment]
recheck

**Review by fblackburn1 — APPROVED** [review]

**Pull request merged**
