### PR TITLE
Added sentinel files to HA plugin

### PR DESCRIPTION
**Pull request by DrPyser**
* HAConfigManager updated to manage sentinel files to reflect HA mode status of the node
* integration tests docker environment updated with a /var/lib/wazo directory

## Test coverage
* wazo_sysconfd/plugins/ha_config/tests/test_ha.py: TestSentinelFilesManager

## Related PRs
* https://github.com/wazo-platform/wazo-upgrade/pull/75
* https://github.com/wazo-platform/xivo-config/pull/79

### CODE REVIEW

**Comment by fblackburn1** [comment]
No need to assign reviewer if the ticket has already been taken

**Review by fblackburn1 — COMMENTED** [review]
Well done. Work as expected :+1:
Can you use single quote to mitigate disparity on same file

**Comment by DrPyser** [comment]
TODO: link to migration script PR in wazo-upgrade

**Comment by DrPyser** [comment]
TODO: add wazo-platform.org documentation PR.

**Review by fblackburn1 — APPROVED** [review]

**Comment by DrPyser** [comment]
https://github.com/wazo-platform/wazo-platform.org/pull/598/files

**Pull request merged**
